AdministratorApp/Models/ServiceForClient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AdministratorApp.Models
{
    public class ServiceForClient
    {
        public int Id { get; set; }

        //Service execution status
        [Display(Name = "Service completed: ")]
        public bool Service_For_Client_Execution_Status { get; set; }

        //Service payment status
        [Display(Name = "Service paid for:")]
        public bool Service_For_Client_Payment_Status { get; set; }

        //Elapsed time
        [Display(Name = "Elapsed time:")]
        public double Service_For_Client_Elapsed_Time { get; set; }

        //Service is measured in minutes
        [DefaultValue(false)]
        public bool Service_For_Client_Time_Type_Minutes { get; set; }

        //Service start date
        [Display(Name = "Service start date:")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime Service_For_Client_Start_Date { get; set; }

        //Date of actual completion of the service
        [Display(Name = "Date of actual completion of the service:")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Service_For_Client_Actual_End_Date { get; set; }

        //Deadline date
        [Display(Name = "Service deadline date:")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Service_For_Client_Deadline_Date { get; set; }

        //Service payment date
        [Display(Name = "Service payment date:")]
        [DisplayFormat(DataFormatString = "{YYYY-MM-DD}", ApplyFormatInEditMode = true)]
        public DateTime Service_For_Client_Payment_Date { get; set; }

        public int ClientId { get; set; }
        public Client Client { get; set; }
        public int ServiceId { get; set; }
        public Service Service { get; set; }
    }
}

AdministratorApp/Controllers/ServiceForClientController.cs
using AdministratorApp.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdministratorApp.Models;

namespace AdministratorApp.Controllers
{
    public class ServiceForClientController : Controller
    {
        private readonly IAdministratorAppRepository db;

        public ServiceForClientController(IAdministratorAppRepository context)
        {
            db = context;
        }

        [HttpGet]
        [Route("ServiceForClient/EditServiceForClient")]
        public async Task<IActionResult> EditServiceForClient(int? client_id, int? service_id, string service_name)
        {
            ViewBag.Name = service_name;
            var service = await db.GetService(service_id.Value);
            ViewBag.Minutes = service.Service_Time_Type_Minutes;

            var serv = await db.ServiceClientGet(client_id.Value, service_id.Value);
            if (serv != null)
            {
                return View(serv);
            }
            else { return NotFound(); }
        }

        [Route("ServiceForClient/EditServiceForClient")]
        [HttpPost]
        public IActionResult EditServiceForClient(ServiceForClient serv, int client_id, int service_id)
        {
            ServiceForClient servcl = db.ServiceClientEditPost(serv, client_id, service_id);
            if (servcl != null)
            {
                return RedirectToAction("ShowAllClients", "Client");
            }
            else { return NotFound(); }
        }

        [Route("ServiceForClient/DeleteServiceForClient")]
        [HttpGet]
        [ActionName("DeleteServiceForClient")]
        public async Task<IActionResult> ServiceClientConfirmDelete(int? client_id, int? service_id)
        {
            if (client_id != null && service_id != null)
            {
                var srcl = await db.ServiceClientGet(client_id.Value, service_id.Value);
                return View(srcl);
            }
            return NotFound();
        }

        [Route("ServiceForClient/DeleteServiceForClient")]
        [HttpPost]
        [ActionName("DeleteServiceForClient")]
        public IActionResult DeleteServiceForClient(int? client_id, int? service_id)
        {
            if (client_id != null && service_id != null)
            {
                db.ServiceClientDelete(client_id, service_id);
                return RedirectToAction("ShowAllClients", "Client");
            }
            return NotFound();
        }
    }
}

AdministratorApp/Views/ServiceForClient/DeleteServiceForClient.cshtml
@model AdministratorApp.Models.ServiceForClient
@using AdministratorApp.Models
<input type="hidden" value="@Model.ServiceId" name="service_id" />
<input type="hidden" value="@Model.ClientId" name="client_id" />
<div>
    <dl class="dl-horizontal">
        <dt>Service to be removed:</dt>
        <dd>
            @Html.DisplayFor(model => model.Service.Service_Name)
        </dd>
    </dl>
</div>
<form asp-controller="ServiceForClient" asp-action="DeleteServiceForClient" asp-route-client_id="@Model.ClientId" asp-route-service_id="@Model.ServiceId" method="post">
    <div class="form-group">
        <input type="submit" value="Delete" />
    </div>
</form>

AdministratorApp/Views/ServiceForClient/EditServiceForClient.cshtml
@model  AdministratorApp.Models.ServiceForClient
<div>
    <dl class="dl-horizontal">
        <dt class="text-black h3">
            @ViewBag.Name (@Model.Client.Client_Name)
        </dt>
    </dl>
</div>
<form asp-action="EditServiceForClient" asp-controller="ServiceForClient">
    <input type="hidden" value="@Model.ServiceId" name="service_id" />
    <input type="hidden" value="@Model.ClientId" name="client_id" />
    <div>
        <table class="table">
            <tr>
                <td>
                    <label asp-for="Service_For_Client_Start_Date" class="control-label"></label>
                </td>
                <td>
                    <input class="form-control" asp-for="Service_For_Client_Start_Date" asp-format="{0:yyyy-MM-ddTHH:mm}" />
                </td>
                <td>
                    <label asp-for="Service_For_Client_Actual_End_Date" class="control-label"></label>
                </td>
                <td>
                    <input class="form-control" asp-for="Service_For_Client_Actual_End_Date" asp-format="{0:yyyy-MM-ddTHH:mm}" />
                </td>
                <td>
                    <label asp-for="Service_For_Client_Deadline_Date" class="control-label"></label>
                </td>
                <td>
                    <input class="form-control" asp-for="Service_For_Client_Deadline_Date" asp-format="{0:yyyy-MM-ddTHH:mm}" />
                </td>
                </tr>
            <tr>
                <td>
                    <label asp-for="Service_For_Client_Payment_Date" class="control-label"></label>
                </td>
                <td>
                    <input class="form-control" asp-for="Service_For_Client_Payment_Date" asp-format="{0:yyyy-MM-ddTHH:mm}" />
                </td>
                <td>
                    <label asp-for="Service_For_Client_Elapsed_Time" class="control-label"></label>
                </td>
                    @if (@ViewBag.Minutes == true)
                    {
                        <td>
                            <input class="form-control" type="time" asp-for="Service_For_Client_Elapsed_Time" asp-format="{0:mm}" />
                            Minutes
                        </td>
                    }
                    else
                    {
                        <td>
                            <input class="form-control" type="time" asp-for="Service_For_Client_Elapsed_Time" asp-format="{0:hh}" />
                            Hours
                        </td>
                    }
            </tr>
            <tr>
                <td>Order is paid:</td>
                <td>
                    @Html.CheckBox("Service_For_Client_Payment_Status", @Model.Service_For_Client_Payment_Status)
                </td>
            </tr>
            <tr>
                <td>Service is done:</td>
                <td>
                    @Html.CheckBox("Service_For_Client_Execution_Status", @Model.Service_For_Client_Execution_Status)
                </td>
             </tr>
        </table>
    </div>
    <div>
        <input type="submit" class=" btn btn-outline-dark" value="Save" />
        <a asp-action="DeleteServiceForClient" asp-controller="ServiceForClient" asp-route-client_id="@Model.ClientId" asp-route-service_id="@Model.ServiceId">
            <span class="btn btn-outline-dark">Delete</span>
        </a>
    </div>
</form>